services:
  nginx:
    build: .
    container_name: reverse-proxy

    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro

    ports:
      - "80:80"

    restart: unless-stopped

    networks:
      - proxy

networks:
  proxy:
    external: true
