services:
  nginx:
    image: ghcr.io/dakardu/reverse-proxy:latest
    container_name: reverse-proxy

    ports:
      - "80:80"

    restart: unless-stopped

    networks:
      - proxy

networks:
  proxy:
    name: proxy
