events {}

http {
    upstream backend {
        server app0:80;
        server app1:80;
        server app2:80;
    }

    server {
        listen 80;

        server_name netservices.local;

        location / {
            proxy_pass http://backend;
        }
    }

    server {
        listen 80;

        server_name portafolio.local;

        location / {
            proxy_pass http://portafolio-frontend;
        }

        location /api/ {
            proxy_pass http://portafolio-backend:3000;
        }
    }

}